### ISSUE TITLE
[Config] Reconfiguration of the linter, code formatter and typescript for a better development experience

### ISSUE THREAD

**Issue by Swiizyy** [BirthdayyBot/BirthdayyBotSapphire#129]
Review all the configuration of these to have superior development experience now

**Comment by nikolaischunk** [comment]
- [ ] Add a Prettier ESLint Workflow that runs on PRs

**Comment by Swiizyy** [comment]
- [ ] Installation of husky
- [ ] Add eslint check

**Comment by Swiizyy** [comment]
### Plugins Eslint

- [ ] Typescript eslint naming convention

**Comment by Swiizyy** [comment]
### Script

- [ ] Docker compose
- [ ] Dockerfile.dev/testing
