### ISSUE TITLE
[Enhancement] Decide on a variable naming convention to use

### ISSUE THREAD

**Issue by nikolaischunk** [BirthdayyBot/BirthdayyBotSapphire#151]
Currently, we have a mix of the different cases used for variable names.
For a better Developer Experience, we should decide on one, and use this in all places.

Reference: https://github.com/kettanaito/naming-cheatsheet#naming-convention

**Comment by Swiizyy** [comment]
Ref: #129

**Comment by Swiizyy** [comment]
Default: camelCase
Class: PascalCase
Env: UPPER_SNAKE_CASE

**Comment by nikolaischunk** [comment]
I would suggest to use `snake_case` for normal variables.
`guild_id` instead of `guildId`
`event_type` instead of `eventType`

**Comment by Swiizyy** [comment]
> I would suggest to use snake_case for normal variables.
> guild_id instead of guildId
> event_type instead of eventType

Personally, I'm not a big fan of this type 😕.
Then in the JavaScript convention it's camelCase.
 The snake-case is normally used in python.

**Comment by Swiizyy** [comment]
If you are afraid to change because you use this one in the database is not serious we can adjust this by using @map() in the prisma schema

**Comment by nikolaischunk** [comment]
alright make sense. but is no priority at the moment. features are more important. this will give huge merge conflicts if two people are working at the same time so lets schedule this for later.

**Comment by Swiizyy** [comment]
> alright make sense. but is no priority at the moment. features are more important. this will give huge merge conflicts if two people are working at the same time so lets schedule this for later.

Yes, I agree 👍
