### ISSUE TITLE
[Enhancement] Clear console from Shard Log Spam

### ISSUE THREAD

**Issue by nikolaischunk** [BirthdayyBot/BirthdayyBotSapphire#175]
Currently, most of the logs we receive are from heartbeats & Shards.
Important information might get lost, so I would suggest to compleatly remove the debug logs of the shards and only leave the `warning` and `error` logs.

@Swiizyy what do you think.

![grafik](https://user-images.githubusercontent.com/58025175/230034786-88a08fea-b7dc-4cb7-a57c-7325b54e4ca4.png)

**Comment by Swiizyy** [comment]
I agree 👌's
