### ISSUE TITLE
[Chore] Fetch dynamic

### ISSUE THREAD

**Issue by Swiizyy** [BirthdayyBot/BirthdayyBotSapphire#195]
Currently we fetch guilds, users, channels in separate functions it might be interesting to create a function that could manage all three dynamically by passing the expected value as a parameter. This would avoid code duplication and simpler error handling.

```ts

// exemple
  const guild = fetchDiscord('guilds', guild.id) // return guild: Guild

```

**Comment by nikolaischunk** [comment]
I dont see the value of this. `getGuildMember`, `gerGuildInformation` etc. is a way clearer naming of the function.

**Comment by Swiizyy** [comment]
Alternative:
Use the Sapphire Resolver with the resolveGuild/resolveUser/resolveChannel functions.
