### ISSUE TITLE
[Bug] Announcement channel is not found

### ISSUE THREAD

**Issue by nikolaischunk** [BirthdayyBot/BirthdayyBotSapphire#269]
![grafik](https://user-images.githubusercontent.com/58025175/236144209-c07e9a5b-65b5-4957-9450-fc55e44e08b1.png)

**Comment by nikolaischunk** [comment]
Not even sure if it is abug, but worth investigating

**Comment by Swiizyy** [comment]
After many tests, this is not a bug, so I am closing this issue
